sudo: required
os: linux
dist: xenial
language: cpp
compiler: gcc

env:
  global:
    - QT_MAJOR=qt59
    - QT_MINOR=qt591
    - QTC_VERSION=${QT_MAJOR}creator
    - QTC_BUILD=/opt/${QT_MAJOR}/
    - QTC_SOURCE=${TRAVIS_BUILD_DIR}/${QTC_VERSION}
    - QTC_LIBRARY_BASENAME=lib/x86_64-linux-gnu
    - PROJECT_PRO_FILE="plugin.pro"
    - QMAKE_PARAMS="-spec linux-g++"

install:
  - echo "Installing ${QTC_VERSION} with ${QT_MINOR}"
  - sudo add-apt-repository -y ppa:beineri/opt-${QT_MINOR}-xenial
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -y update -qq
  - sudo apt-get install ${QTC_VERSION} gcc-4.8 g++-4.8 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90 
  - apt source ${QTC_VERSION} --tar-only
  - mkdir -p ${QTC_SOURCE} && tar xf ${QTC_VERSION}* -C ${QTC_SOURCE} --strip-components=1

script:
  - source /opt/${QT_MAJOR}/bin/qt${QT_MAJOR}-env.sh
  - echo "Executing qmake..."
  - qmake ${PROJECT_PRO_FILE} -r ${QMAKE_PARAMS}
  - make

